name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Maven package
        run: mvn -B package